name: "Build docker image and push"
description: "Build Docker image and push to Artifact Registry"
inputs:
  workload_identity_provider:
    description: "Workload Identity Provider ID"
    required: true
  service_account:
    description: "Service account ID"
    required: true
  registry:
    description: "Registry name of Artifact Registry"
    required: false
    default: "asia-northeast1-docker.pkg.dev"
  docker_tag:
    description: "Docker tag name"
    required: false
  docker_build_args:
    description: "Docker build args"
    required: false
  working_dir:
    description: "specify working directory"
    default: "./"
    required: false

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - id: Auth
      uses: "google-github-actions/auth@v2"
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Set up Cloud SDK
      uses: "google-github-actions/setup-gcloud@v2"

    - name: Configure docker for artifact registry
      shell: bash
      run: gcloud auth configure-docker ${{ inputs.registry }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64
        push: true
        tags: ${{ inputs.docker_tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: ${{ inputs.docker_build_args }}
        context: ${{ inputs.working_dir }}
